# Generated by Django 5.1.4 on 2025-01-06 12:57

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServerSidePage', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_logincred',
            name='username',
            field=models.CharField(default='default_user', error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user_logincred',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='user_logincred',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='custom_user_loginCred_set', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='user_logincred',
            name='name',
            field=models.CharField(default='default_user', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='user_logincred',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='custom_user_loginCred_permissions_set', to='auth.permission'),
        ),
    ]
